### ISSUE TITLE
linux_aarch64_python3.6 failed

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/configparser-feedstock#26]
The `linux_aarch64_python3.6` failed in PR ( https://github.com/conda-forge/configparser-feedstock/pull/22 ) despite not really changing that build (only enabled Windows builds). Plus [that build passed on `master`]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=15975&view=logs ) recently. Have copied down the traceback below and linked the log with details.

```python
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/conda_build/environ.py", line 753, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/opt/conda/lib/python3.7/site-packages/conda/common/io.py", line 46, in decorated
    return f(*args, **kwds)
  File "/opt/conda/lib/python3.7/site-packages/conda/plan.py", line 541, in install_actions
    txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
  File "/opt/conda/lib/python3.7/site-packages/conda/core/solve.py", line 518, in solve_for_transaction
    force_remove, force_reinstall)
  File "/opt/conda/lib/python3.7/site-packages/conda/core/solve.py", line 451, in solve_for_diff
    final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)
  File "/opt/conda/lib/python3.7/site-packages/conda/core/solve.py", line 331, in solve_final_state
    conflicting_specs = r.get_conflicting_specs(tuple(final_environment_specs))
  File "/opt/conda/lib/python3.7/site-packages/conda/resolve.py", line 746, in get_conflicting_specs
    reduced_index = self.get_reduced_index(specs)
  File "/opt/conda/lib/python3.7/site-packages/conda/resolve.py", line 254, in get_reduced_index
    specs, features = self.verify_specs(specs)
  File "/opt/conda/lib/python3.7/site-packages/conda/resolve.py", line 172, in verify_specs
    raise ResolvePackageNotFound(bad_deps)
conda.exceptions.ResolvePackageNotFound: 
  - python=3.6

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 456, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 447, in execute
    verify=args.verify, variants=args.variants)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/api.py", line 208, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 2311, in build_tree
    notest=notest,
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 1324, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "/opt/conda/lib/python3.7/site-packages/conda_build/render.py", line 735, in expand_outputs
    for (output_dict, m) in _m.copy().get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "/opt/conda/lib/python3.7/site-packages/conda_build/metadata.py", line 2038, in get_output_metadata_set
    bypass_env_check=bypass_env_check)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/metadata.py", line 721, in finalize_outputs_pass
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/render.py", line 509, in finalize_metadata
    exclude_pattern)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/render.py", line 393, in add_upstream_pins
    permit_unsatisfiable_variants, exclude_pattern)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/render.py", line 359, in _read_upstream_pin_files
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/render.py", line 143, in get_env_dependencies
    channel_urls=tuple(m.config.channel_urls))
  File "/opt/conda/lib/python3.7/site-packages/conda_build/environ.py", line 755, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-aarch64: {'python=3.6'}
##[error]Bash exited with code '1'.
```

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=16110

**Comment by jakirkham** [comment]
Still happening on `master`. Any thoughts @conda-forge/arm-arch?

ref: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=16113

**Comment by jjhelmus** [comment]
The python 3.6 package was deleted from Anaconda.org and a new version uploaded.  This configparser build likely occured in the period of time when the package was missing.  Re-running the build now should succeed.

**Comment by jakirkham** [comment]
Thanks for the update, @jjhelmus. Do you know how one goes about restarting a build on Azure? I'm not seeing a button for this.

**Comment by jjhelmus** [comment]
@mariusvniekerk mentioned he restarted the build.  He can give details on how this process work much better than I can.

**Comment by jakirkham** [comment]
Ok, I'll ask him. There was a PR I was wanting to restart a build for, but I just gave up and merged since it sounds like it shouldn't be an issue on `master`.

**Comment by jakirkham** [comment]
Things look good now. Thanks all! :)

ref: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=16171
